import type { BusStop } from './bus-stops';

export const MASHHAD_BRT_STOPS: BusStop[] = [
  // --- خط ۱ بی‌آرتی مشهد (پایانه امام رضا (ع) تا پایانه طبرسی) ---
  {
    id: 'mashhad-brt-1-01',
    name: 'پایانه امام رضا (ع)',
    latinName: 'Imam Reza Terminal',
    address: 'مشهد، بزرگراه شهید قاسم سلیمانی، پایانه مسافربری امام رضا (ع)',
    coordinate: [59.5860284, 36.2635271],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'به سمت پایانه طبرسی',
    stationCode: 'BRT-MHD-101',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 3.5,
  },
  {
    id: 'mashhad-brt-1-02',
    name: 'میدان پانزده خرداد',
    latinName: '15 Khordad Square',
    address: 'مشهد، میدان پانزده خرداد (فلکه ضد)',
    coordinate: [59.5932, 36.2685],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-102',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 2.8,
  },
  {
    id: 'mashhad-brt-1-03',
    name: 'میدان بسیج (فلکه برق)',
    latinName: 'Basij Square',
    address: 'مشهد، میدان بسیج، تقاطع خیابان امام رضا و فدائیان اسلام',
    coordinate: [59.603463, 36.2736315],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-103',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 1.8,
  },
  {
    id: 'mashhad-brt-1-04',
    name: 'چهارراه نخریسی (۱۷ شهریور)',
    latinName: 'Nakhresi Cross / 17 Shahrivar',
    address: 'مشهد، تقاطع خیابان امام رضا و ۱۷ شهریور',
    coordinate: [59.6105, 36.278],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-104',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 1.2,
  },
  {
    id: 'mashhad-brt-1-05',
    name: 'چهارراه دانش',
    latinName: 'Danesh Cross',
    address: 'مشهد، خیابان امام رضا، تقاطع دانش شرقی و غربی',
    coordinate: [59.6125, 36.2825],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-105',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 0.8,
  },
  {
    id: 'mashhad-brt-1-06',
    name: 'میدان بیت‌المقدس (فلکه آب)',
    latinName: 'Beit-ol-Moqaddas Square (Falak-e Ab)',
    address: 'مشهد، میدان بیت‌المقدس، ورودی باب الرضا حرم مطهر',
    coordinate: [59.6145, 36.2872],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-106',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 0.2,
  },
  {
    id: 'mashhad-brt-1-07',
    name: 'حرم مطهر - باب الجواد (ع)',
    latinName: 'Holy Shrine - Babol-Javad',
    address: 'مشهد، زیرگذر حرم مطهر، خروجی باب الجواد',
    coordinate: [59.6110962, 36.2856931],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-107',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 0.3,
  },
  {
    id: 'mashhad-brt-1-08',
    name: 'حرم مطهر - بست شیرازی',
    latinName: 'Holy Shrine - Bast Shirazi',
    address: 'مشهد، خیابان شیرازی، ورودی بست شیخ طوسی',
    coordinate: [59.6132102, 36.2902805],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-108',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 0.4,
  },
  {
    id: 'mashhad-brt-1-09',
    name: 'چهارراه شهدا',
    latinName: 'Shohada Cross',
    address: 'مشهد، تقاطع خیابان شیرازی و آزادی',
    coordinate: [59.61, 36.2935],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-109',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 0.9,
  },
  {
    id: 'mashhad-brt-1-10',
    name: 'میدان شهدا',
    latinName: 'Shohada Square',
    address: 'مشهد، میدان شهدا، پایانه اتوبوسرانی میدان شهدا',
    coordinate: [59.6074725, 36.2977387],
    lines: 'خط ۱ بی‌آرتی (۸۰۰) و خط ۴ بی‌آرتی',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-110',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 1.5,
  },
  {
    id: 'mashhad-brt-1-11',
    name: 'چهارراه مقدم (طبرسی)',
    latinName: 'Moghadam Cross (Tabarsi)',
    address: 'مشهد، ابتدای بلوار طبرسی جنوبی، تقاطع مقدم',
    coordinate: [59.62, 36.3015],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-111',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 2.1,
  },
  {
    id: 'mashhad-brt-1-12',
    name: 'تقاطع گاز و طبرسی',
    latinName: 'Gaz & Tabarsi Cross',
    address: 'مشهد، بلوار طبرسی، تقاطع بلوار گاز',
    coordinate: [59.6443514, 36.3063643],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-112',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 3.8,
  },
  {
    id: 'mashhad-brt-1-13',
    name: 'ایستگاه فتاح (طبرسی)',
    latinName: 'Fattah Station',
    address: 'مشهد، بلوار طبرسی شمالی، نزدیک شهید فتاح',
    coordinate: [59.655, 36.312],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-113',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 4.9,
  },
  {
    id: 'mashhad-brt-1-14',
    name: 'ایستگاه نوغان (طبرسی)',
    latinName: 'Noghan Station',
    address: 'مشهد، بلوار طبرسی شمالی، تقاطع نوغان',
    coordinate: [59.667, 36.319],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-114',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 6.2,
  },
  {
    id: 'mashhad-brt-1-15',
    name: 'پایانه طبرسی',
    latinName: 'Tabarsi Terminal',
    address: 'مشهد، انتهای بلوار طبرسی شمالی، پایانه طبرسی',
    coordinate: [59.687537, 36.328917],
    lines: 'خط ۱ بی‌آرتی (۸۰۰)',
    isBRT: true,
    brtLine: 'خط ۱ بی‌آرتی',
    direction: 'به سمت پایانه امام رضا',
    stationCode: 'BRT-MHD-115',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 8.5,
  },

  // --- خط ۲ بی‌آرتی مشهد (پایانه الهیه تا پایانه مصلی / خطوط ۸۳۰ و ۸۳۱) ---
  {
    id: 'mashhad-brt-2-01',
    name: 'پایانه الهیه',
    latinName: 'Elahiye Terminal',
    address: 'مشهد، انتهای بلوار الهیه، پایانه اتوبوسرانی الهیه',
    coordinate: [59.4785672, 36.3718895],
    lines: 'خط ۲ بی‌آرتی (۸۳۰/۸۳۱)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'به سمت پایانه مصلی',
    stationCode: 'BRT-MHD-201',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 12.5,
  },
  {
    id: 'mashhad-brt-2-02',
    name: 'میدان شهید گمنام (الهیه)',
    latinName: 'Shahid Gomnam Square',
    address: 'مشهد، بلوار الهیه، میدان شهید گمنام',
    coordinate: [59.489, 36.366],
    lines: 'خط ۲ بی‌آرتی (۸۳۰)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-202',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 11.2,
  },
  {
    id: 'mashhad-brt-2-03',
    name: 'چهارراه مخابرات (قاسم‌آباد)',
    latinName: 'Mokhaberat Cross',
    address: 'مشهد، قاسم‌آباد (شهرک غرب)، تقاطع شریعتی و فلاحی',
    coordinate: [59.501, 36.362],
    lines: 'خط ۲ بی‌آرتی (۸۳۰)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-203',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 9.8,
  },
  {
    id: 'mashhad-brt-2-04',
    name: 'چهارراه امامیه',
    latinName: 'Emamiyeh Cross',
    address: 'مشهد، قاسم‌آباد، تقاطع بلوار امامیه و شاهد',
    coordinate: [59.5168211, 36.360054],
    lines: 'خط ۲ بی‌آرتی (۸۳۰/۸۳۱)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-204',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 8.5,
  },
  {
    id: 'mashhad-brt-2-05',
    name: 'میدان آزادی (پارک ملت)',
    latinName: 'Azadi Square (Mellat Park)',
    address: 'مشهد، میدان آزادی، ورودی پارک ملت و ایستگاه تقاطعی خط ۱ مترو',
    coordinate: [59.5396901, 36.3103931],
    lines: 'خط ۲ بی‌آرتی (۸۳۰/۸۳۱)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-205',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 5.5,
  },
  {
    id: 'mashhad-brt-2-06',
    name: 'میدان استقلال',
    latinName: 'Esteghlal Square',
    address: 'مشهد، بلوار آزادی، میدان استقلال',
    coordinate: [59.548, 36.318],
    lines: 'خط ۲ بی‌آرتی (۸۳۰)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-206',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 4.8,
  },
  {
    id: 'mashhad-brt-2-07',
    name: 'بلوار سازمان آب (شهید صادقی)',
    latinName: 'Sazman Ab Boulevard',
    address: 'مشهد، بلوار شهید صادقی، تقاطع سازمان آب',
    coordinate: [59.563, 36.312],
    lines: 'خط ۲ بی‌آرتی (۸۳۰)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-207',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 3.8,
  },
  {
    id: 'mashhad-brt-2-08',
    name: 'میدان احمدآباد',
    latinName: 'Ahmadabad Square',
    address: 'مشهد، میدان احمدآباد، ورودی ایستگاه خط ۱ مترو',
    coordinate: [59.5736577, 36.2989723],
    lines: 'خط ۲ بی‌آرتی (۸۳۱)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-208',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 3.2,
  },
  {
    id: 'mashhad-brt-2-09',
    name: 'چهارراه دکترا (ابن سینا)',
    latinName: 'Doktora Cross',
    address: 'مشهد، تقاطع خیابان ابن سینا و پاستور',
    coordinate: [59.588, 36.293],
    lines: 'خط ۲ بی‌آرتی (۸۳۱)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-209',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 2.2,
  },
  {
    id: 'mashhad-brt-2-10',
    name: 'میدان شریعتی (تقی‌آباد)',
    latinName: 'Shariati Square (Taghiabad)',
    address: 'مشهد، میدان دکتر علی شریعتی، ایستگاه تقاطعی خطوط ۱ و ۲ مترو',
    coordinate: [59.591, 36.291],
    lines: 'خط ۲ بی‌آرتی (۸۳۱)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-210',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 1.9,
  },
  {
    id: 'mashhad-brt-2-11',
    name: 'میدان توحید',
    latinName: 'Tohid Square',
    address: 'مشهد، میدان توحید (فلکه دروازه قوچان)',
    coordinate: [59.593, 36.302],
    lines: 'خط ۲ بی‌آرتی (۸۳۰)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-211',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 1.8,
  },
  {
    id: 'mashhad-brt-2-12',
    name: 'میدان ۱۰ دی',
    latinName: '10 Dey Square',
    address: 'مشهد، خیابان امام خمینی، میدان ۱۰ دی',
    coordinate: [59.598, 36.287],
    lines: 'خط ۲ بی‌آرتی (۸۳۱)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-212',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 1.2,
  },
  {
    id: 'mashhad-brt-2-13',
    name: 'بلوار مصلی',
    latinName: 'Mosalla Boulevard',
    address: 'مشهد، بلوار مصلی، نزدیک تقاطع چمن',
    coordinate: [59.647326, 36.2609361],
    lines: 'خط ۲ بی‌آرتی (۸۳۰/۸۳۱)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-213',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 4.5,
  },
  {
    id: 'mashhad-brt-2-14',
    name: 'پایانه مصلی',
    latinName: 'Mosalla Terminal',
    address: 'مشهد، انتهای بلوار مصلی، پایانه اتوبوسرانی مصلی',
    coordinate: [59.6386152, 36.2673122],
    lines: 'خط ۲ بی‌آرتی (۸۳۰/۸۳۱)',
    isBRT: true,
    brtLine: 'خط ۲ بی‌آرتی',
    direction: 'به سمت پایانه الهیه',
    stationCode: 'BRT-MHD-214',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 4.8,
  },

  // --- خطوط ۳ و ۴ بی‌آرتی مشهد (خواجه ربیع، الماس شرق و شهید رجایی) ---
  {
    id: 'mashhad-brt-3-01',
    name: 'آرامگاه خواجه ربیع',
    latinName: 'Khajeh Rabi Tomb',
    address: 'مشهد، انتهای خیابان خواجه ربیع، میدان آرامگاه خواجه ربیع',
    coordinate: [59.6280729, 36.3404959],
    lines: 'خط ۴ بی‌آرتی',
    isBRT: true,
    brtLine: 'خط ۴ بی‌آرتی',
    direction: 'به سمت میدان شهدا و حرم',
    stationCode: 'BRT-MHD-401',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 7.5,
  },
  {
    id: 'mashhad-brt-3-02',
    name: 'میدان امام حسین (ع)',
    latinName: 'Imam Hossein Square',
    address: 'مشهد، بزرگراه شهید چراغچی، تقاطع بلوار خواجه ربیع',
    coordinate: [59.632, 36.335],
    lines: 'خط ۴ بی‌آرتی',
    isBRT: true,
    brtLine: 'خط ۴ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-402',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 6.2,
  },
  {
    id: 'mashhad-brt-3-03',
    name: 'مجتمع تجاری الماس شرق',
    latinName: 'Almas Shargh Commercial Complex',
    address: 'مشهد، انتهای بلوار خیام شمالی، منطقه سپاد',
    coordinate: [59.5957886, 36.3457947],
    lines: 'خط ۳ بی‌آرتی',
    isBRT: true,
    brtLine: 'خط ۳ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-301',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 6.8,
  },
  {
    id: 'mashhad-brt-3-04',
    name: 'پایانه شهید مفتح',
    latinName: 'Shahid Mofatteh Terminal',
    address: 'مشهد، انتهای بلوار شهید مفتح، پایانه اتوبوسرانی',
    coordinate: [59.6626188, 36.287005],
    lines: 'خط ۳ بی‌آرتی',
    isBRT: true,
    brtLine: 'خط ۳ بی‌آرتی',
    direction: 'دو طرفه',
    stationCode: 'BRT-MHD-302',
    seat: 'دارد',
    shelter: 'دارد',
    light: 'دارد',
    disabledAccess: 'دارد',
    transportMode: 'اتوبوس تندرو (BRT)',
    city: 'Mashhad',
    dist: 5.8,
  },
];
